### ISSUE TITLE
Trouble when starting fmp4streamer

### ISSUE THREAD

**Issue by jpelletier** [soyersoyer/fmp4streamer#15]
Platform: Raspberry pi 2W
OS: Raspberry Pi, Bullseye
Camera v1.3
Hardware works fine 
Camera autodetect = 1

Configuration file:
[fmp4.txt](https://github.com/soyersoyer/fmp4streamer/files/12447754/fmp4.txt)

Here is the messages displayed when running fmp4streamer
![Capture d’écran de 2023-08-27 06-07-48](https://github.com/soyersoyer/fmp4streamer/assets/788008/9c2d163d-b3a8-482d-9dd1-05764e1fca24)

How can I make it run?

**Comment by soyersoyer** [comment]
If you are using Bullseye, please read the Readme's [Raspberry section](https://github.com/soyersoyer/fmp4streamer#raspberry)

**Comment by jpelletier** [comment]
> If you are using Bullseye, please read the Readme's [Raspberry section](https://github.com/soyersoyer/fmp4streamer#raspberry)

After enabling legacy support, I got this:
python fmp4streamer.py 
Waiting for the first h264 frame...Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/slicer/Public/src/fmp4streamer-3.4.7/v4l2camera.py", line 298, in run
    self.start_capturing()
  File "/home/slicer/Public/src/fmp4streamer-3.4.7/v4l2camera.py", line 268, in start_capturing
    self.capture_loop()
  File "/home/slicer/Public/src/fmp4streamer-3.4.7/v4l2camera.py", line 244, in capture_loop
    ioctl(self.fd, v4l2.VIDIOC_QBUF, buf)
OSError: [Errno 14] Bad address

**Comment by TobiasFriberg** [comment]
I'm getting a similar error

```
WARNING:root:Couldn't read fmp4streamer.conf, using default config
Waiting for the first h264 frame...Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/pi/fmp4streamer-3.4.7/v4l2camera.py", line 298, in run
    self.start_capturing()
  File "/home/pi/fmp4streamer-3.4.7/v4l2camera.py", line 267, in start_capturing
    ioctl(self.fd, v4l2.VIDIOC_STREAMON, struct.pack('I', v4l2.V4L2_BUF_TYPE_VIDEO_CAPTURE))
OSError: [Errno 22] Invalid argument
```
